######################################################################
# Automatically generated by qmake (1.07a) Sat Apr 8 14:34:18 2006
######################################################################

TEMPLATE = app
CONFIG  += console warn_on
CONFIG  -= qt
INCLUDEPATH += ../../rllib/rlsvg

# Input
HEADERS += ../../rllib/rlsvg/rlsvgcat.h
SOURCES += ../../rllib/rlsvg/rlsvgcat.cpp
TARGET = rlsvgcat

include(../../common.pri)
msvc {
    DESTDIR = $${PVB_OUT_DIR}
}
