######################################################################
# Automatically generated by qmake (2.01a) Fr. Feb 24 11:54:45 2012
######################################################################

TEMPLATE = app
CONFIG  += console warn_on
CONFIG  -= qt
TARGET = ../../bin/pvmore 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

include(../../common.pri)
msvc {
    TARGET = pvmore
    DESTDIR = $${PVB_OUT_DIR}
}
